name: oran-functional-test-case

on:
  workflow_dispatch:
    # For Branch-Protection check. Only the default branch is supported. See
    # https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection
    inputs:
      GERRIT_BRANCH:
        description: 'Branch that change is against'
        required: false
        type: string
      GERRIT_CHANGE_ID:
        description: 'The ID for the change'
        required: false
        type: string
      GERRIT_CHANGE_NUMBER:
        description: 'The Gerrit number'
        required: false
        type: string
      GERRIT_CHANGE_URL:
        description: 'URL to the change'
        required: false
        type: string
      GERRIT_EVENT_TYPE:
        description: 'Gerrit event type'
        required: false
        type: string
      GERRIT_PATCHSET_NUMBER:
        description: 'The patch number for the change'
        required: false
        type: string
      GERRIT_PATCHSET_REVISION:
        description: 'The revision sha'
        required: false
        type: string
      GERRIT_PROJECT:
        description: 'Project in Gerrit'
        required: false
        type: string
      GERRIT_REFSPEC:
        description: 'Gerrit refspec of change'
        required: false
        type: string
        
concurrency:
  group: ${{ github.event.inputs.GERRIT_CHANGE_ID || github.run_id }}
  cancel-in-progress: true

jobs:
  ftc-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository to build
      - name: Checkout ccsdk-oran Maven Project Repository
        uses: lfit/checkout-gerrit-change-action@v0.5
        with:
          gerrit-refspec: ${{ inputs.GERRIT_REFSPEC }}
          gerrit-url: ${{ inputs.GERRIT_CHANGE_URL }}
          gerrit-project: ${{ inputs.GERRIT_PROJECT }}
          ref: ${{ inputs.GERRIT_BRANCH }}

      # Step 2: Set up JDK for Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Or 'zulu' or 'adopt'

      # Step 3: Run Maven build
      - name: Build a1-policy-management image with Maven
        run: |
          cd a1-policy-management
          mvn clean install -Dmaven.test.skip=true -Ddocker.skip.push=true

      # Step 4: Run FTC Job
      - name: Run FTC tests with the local a1-policy image
        run: |
          git clone https://gerrit.o-ran-sc.org/r/nonrtric
          cd nonrtric/test/auto-test
          git pull https://gerrit.o-ran-sc.org/r/nonrtric refs/changes/17/13617/1
          chmod +x ./onap-verify-jobs.sh
          sudo bash ./onap-verify-jobs.sh

      # Step 5: uploading the logs
      - name: uploading the logs
        uses: actions/upload-artifact@v4
        with:
          name: FTC10-Logs
          retention-days: 3
          path: nonrtric/test/auto-test/logs
