name: oran-functional-test-case

on:
  #  pull_request:
  #    branches:
  #      - main
  workflow_dispatch:
    # For Branch-Protection check. Only the default branch is supported. See
    # https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection
    inputs:
      GERRIT_BRANCH:
        description: 'Branch that change is against'
        required: false
        type: string
      #      GERRIT_CHANGE_ID:
      #        description: 'The ID for the change'
      #        required: true
      #        type: string
      #      GERRIT_CHANGE_NUMBER:
      #        description: 'The Gerrit number'
      #        required: true
      #        type: string
      GERRIT_CHANGE_URL:
        description: 'URL to the change'
        required: false
        type: string
      #      GERRIT_EVENT_TYPE:
      #        description: 'Gerrit event type'
      #        required: true
      #        type: string
      #      GERRIT_PATCHSET_NUMBER:
      #        description: 'The patch number for the change'
      #        required: true
      #        type: string
      #      GERRIT_PATCHSET_REVISION:
      #        description: 'The revision sha'
      #        required: true
      #        type: string
      GERRIT_PROJECT:
        description: 'Project in Gerrit'
        required: false
        type: string
      GERRIT_REFSPEC:
        description: 'Gerrit refspec of change'
        required: false
        type: string

jobs:
  ftc-run:
    runs-on: ubuntu-22.04

    steps:
      # Step 2: Checkout the repository to build
      - name: Checkout Maven Project Repository
        uses: lfit/checkout-gerrit-change-action@v0.5
        with:
          gerrit-refspec: ${{ inputs.GERRIT_REFSPEC }}
          gerrit-url: ${{ inputs.GERRIT_CHANGE_URL }}
          gerrit-project: ${{ inputs.GERRIT_PROJECT }}
          ref: ${{ inputs.GERRIT_BRANCH }}

      # Step 3: Set up JDK for Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Or 'zulu' or 'adopt'

      # Step 4: Run Maven build
      - name: print docker image before
        run: |
          echo " printing docker images before"
          docker images 

      # Step 5: Run Maven build
      - name: Build with Maven
        run: |
          cd a1-policy-management
          mvn clean install -DskipTests=true
      
      # Step 6: Run Maven build
      - name: print docker image
        run: |
          echo " printing docker images"
          docker images

      # Step 7: Run FTC Job
      - name: Run FTC job
        # working-directory: ${{ github.workspace }}/test/auto-test
        run: |
          git clone https://gerrit.o-ran-sc.org/r/nonrtric
          cd nonrtric/test/auto-test
          git pull https://gerrit.o-ran-sc.org/r/nonrtric refs/changes/64/13564/4
          chmod +x ./onap-verify-jobs.sh
          sudo bash ./onap-verify-jobs.sh
          
      # Step 8: Run Maven build
      - name: print docker logs
        run: |
          echo " printing docker logs of policy management service"
          docker ps 
          echo "--------------------------------------"
          docker logs policymanagementservice
